name: recipe_finder
description: A feature-rich Recipe Finder app using TheMealDB API and Hive for persistence.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  google_fonts: ^6.2.1

  # UPDATED
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.0.0

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

  # Hive codegen
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
